import Header from '@/components/Header'
import Footer from '@/components/Footer'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy - Knowtly',
  description: 'Knowtly Privacy Policy. Learn how we collect, use, and protect your personal information.',
  robots: {
    index: true,
    follow: true,
  },
}

export default function PrivacyPage() {
  return (
    <>
      <Header />
      <main className="min-h-screen bg-background-dark">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-24">
          <div className="bg-surface-dark rounded-2xl p-8 md:p-12 border border-white/10 shadow-2xl">
            <h1 className="text-4xl md:text-5xl font-black text-white mb-4">Privacy Policy</h1>

            <div className="prose prose-invert max-w-none space-y-8 text-gray-300">
              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Introduction</h2>
                <p className="leading-relaxed">
                  Knowtly, Our Team (&quot;Company&quot;, &quot;us&quot;, &quot;we&quot;, or &quot;our&quot;), operates https://knowtly.app/ (hereinafter referred to as &quot;Service&quot;).
                </p>
                <p className="leading-relaxed mt-4">
                  Our Privacy Policy governs your visit to https://knowtly.app and explains how we collect, safeguard, and disclose information that results from your use of our Service.
                </p>
                <p className="leading-relaxed mt-4">
                  By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Definitions</h2>
                <p className="leading-relaxed">
                  <strong>Service</strong> refers to the https://knowtly.app/ website, operated by Knowtly.
                </p>
                <p className="leading-relaxed mt-4">
                  <strong>Personal Data</strong> means data about a living individual who can be identified from that data (or from that data and other information either in our possession or likely to come into our possession).
                </p>
                <p className="leading-relaxed mt-4">
                  <strong>Usage Data</strong> is data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                </p>
                <p className="leading-relaxed mt-4">
                  <strong>Cookies</strong> are small files stored on your device (computer or mobile device).
                </p>
                <p className="leading-relaxed mt-4">
                  <strong>Data Controller</strong> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For this Privacy Policy, we are a Data Controller of your data.
                </p>
                <p className="leading-relaxed mt-4">
                  <strong>Data Processors</strong> (or Service Providers) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
                </p>
                <p className="leading-relaxed mt-4">
                  <strong>Data Subject</strong> is any living individual who is the subject of Personal Data.
                </p>
                <p className="leading-relaxed mt-4">
                  <strong>The User</strong> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Information Collection and Use</h2>
                <p className="leading-relaxed">
                  We collect several different types of information for various purposes to provide and improve our Service to you.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Types of Data Collected</h2>
                <h3 className="text-xl font-semibold text-white mt-6 mb-3">Personal Data</h3>
                <p className="leading-relaxed">
                  While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (&quot;Personal Data&quot;). Personally identifiable information may include, but is not limited to:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4 mt-4">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Cookies and Usage Data</li>
                </ul>
                <p className="leading-relaxed mt-4">
                  We may use your Personal Data to contact you with newsletters, marketing or promotional materials, and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or by emailing support@knowtly.app
                </p>

                <h3 className="text-xl font-semibold text-white mt-6 mb-3">Usage Data</h3>
                <p className="leading-relaxed">
                  We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device (&quot;Usage Data&quot;).
                </p>
                <p className="leading-relaxed mt-4">
                  This Usage Data may include information such as your computer&apos;s Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.
                </p>
                <p className="leading-relaxed mt-4">
                  When you access the Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device&apos;s unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers, and other diagnostic data.
                </p>

                <h3 className="text-xl font-semibold text-white mt-6 mb-3">Tracking Cookies Data</h3>
                <p className="leading-relaxed">
                  We use cookies and similar tracking technologies to track the activity on our Service, and we hold certain information.
                </p>
                <p className="leading-relaxed mt-4">
                  Cookies are files with a small amount of data, which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used, such as beacons, tags, and scripts to collect and track information and to improve and analyze our Service.
                </p>
                <p className="leading-relaxed mt-4">
                  You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                </p>
                <p className="leading-relaxed mt-4">Examples of Cookies we use:</p>
                <ul className="list-disc list-inside space-y-2 ml-4 mt-2">
                  <li><strong>Session Cookies:</strong> We use Session Cookies to operate our Service.</li>
                  <li><strong>Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various settings.</li>
                  <li><strong>Security Cookies:</strong> We use Security Cookies for security purposes.</li>
                  <li><strong>Advertising Cookies:</strong> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Use of Data</h2>
                <p className="leading-relaxed mb-4">Knowtly.app uses the collected data for various purposes:</p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>to provide and maintain our Service;</li>
                  <li>to notify you about changes to our Service;</li>
                  <li>to allow you to participate in interactive features of our Service when you choose to do so;</li>
                  <li>to provide customer support;</li>
                  <li>to gather analysis or valuable information so that we can improve our Service;</li>
                  <li>to monitor the usage of our Service;</li>
                  <li>to detect, prevent, and address technical issues;</li>
                  <li>to fulfill any other purpose for which you provide it;</li>
                  <li>to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
                  <li>to provide you with notices about your account and/or subscription, including expiration and renewal notices, email instructions, etc.;</li>
                  <li>to provide you with news, special offers, and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or enquired abou,t unless you have opted not to receive such information;</li>
                  <li>in any other way we may describe when you provide the information;</li>
                  <li>for any other purpose with your consent.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Retention of Data</h2>
                <p className="leading-relaxed">
                  We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                </p>
                <p className="leading-relaxed mt-4">
                  We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Transfer of Data</h2>
                <p className="leading-relaxed">
                  Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
                </p>
                <p className="leading-relaxed mt-4">
                  If you are located outside India or the United States and choose to provide information to us, please note that we may transfer the data, including Personal Data, to India or the United States and process it there.
                </p>
                <p className="leading-relaxed mt-4">
                  Your consent to this Privacy Policy, followed by your submission of such information, represents your agreement to that transfer.
                </p>
                <p className="leading-relaxed mt-4">
                  Knowtly.app will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy, and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place, including the security of your data and other personal information.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Disclosure of Data</h2>
                <p className="leading-relaxed mb-4">We may disclose personal information that we collect, or you provide:</p>

                <h3 className="text-xl font-semibold text-white mt-6 mb-3">Disclosure for Law Enforcement</h3>
                <p className="leading-relaxed">
                  Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
                </p>

                <h3 className="text-xl font-semibold text-white mt-6 mb-3">Business Transaction</h3>
                <p className="leading-relaxed">
                  If we or our subsidiaries are involved in a merger, acquisition, or asset sale, your Personal Data may be transferred.
                </p>

                <h3 className="text-xl font-semibold text-white mt-6 mb-3">Other cases</h3>
                <p className="leading-relaxed mb-4">We may also disclose your information:</p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>to fulfill the purpose for which you provide it;</li>
                  <li>for including your company&apos;s logo on our website;</li>
                  <li>for any other purpose with your consent.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Security of Data</h2>
                <p className="leading-relaxed">
                  The security of your data is important to us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Your Data Protection Rights Under the General Data Protection Regulation (GDPR)</h2>
                <p className="leading-relaxed">
                  If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.
                </p>
                <p className="leading-relaxed mt-4">
                  We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
                </p>
                <p className="leading-relaxed mt-4">
                  If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at support@knowtly.app.
                </p>
                <p className="leading-relaxed mt-4 mb-4">In certain circumstances, you have the following data protection rights:</p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>the right to access, update, or delete the information we have on you;</li>
                  <li>the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</li>
                  <li>the right to object. You have the right to object to our processing of your Personal Data;</li>
                  <li>the right of restriction. You have the right to request that we restrict the processing of your personal information;</li>
                  <li>the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable, and commonly used format;</li>
                  <li>the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information.</li>
                </ul>
                <p className="leading-relaxed mt-4">
                  Please note that we may ask you to verify your identity before responding to such requests.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</h2>
                <p className="leading-relaxed">
                  CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy.
                </p>
                <p className="leading-relaxed mt-4 mb-4">According to CalOPPA, we agree to the following:</p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Users can visit our site anonymously.</li>
                  <li>Our Privacy Policy link includes the word &quot;Privacy&quot;, and can easily be found on the page specified above on the home page of our website.</li>
                  <li>Users will be notified of any privacy policy changes on our Privacy Policy Page.</li>
                  <li>Users are able to change their personal information by emailing us at support@knowtly.app.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Our Policy on &quot;Do Not Track&quot; Signals</h2>
                <p className="leading-relaxed">
                  We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Service Providers</h2>
                <p className="leading-relaxed">
                  We may employ third-party companies and individuals to facilitate our Service (&quot;Service Providers&quot;), provide Service on our behalf, perform Service-related services, or assist us in analysing how our Service is used.
                </p>
                <p className="leading-relaxed mt-4">
                  These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Analytics</h2>
                <p className="leading-relaxed">
                  We may use third-party Service Providers to monitor and analyze the use of our Service.
                </p>

                <h3 className="text-xl font-semibold text-white mt-6 mb-3">Google Analytics</h3>
                <p className="leading-relaxed">
                  Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.
                </p>
                <p className="leading-relaxed mt-4">
                  For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">AI and Data Processing</h2>
                <p className="leading-relaxed">
                  We use third-party Artificial Intelligence (AI) services to provide the core functionality of our Service.
                </p>
                <div className="bg-surface-light/50 p-6 rounded-xl border border-white/10 mt-4">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-white/10">
                        <th className="text-left py-2 text-white font-semibold">Tool</th>
                        <th className="text-left py-2 text-white font-semibold">Privacy Policy</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr className="border-b border-white/5">
                        <td className="py-2">OpenAI</td>
                        <td className="py-2">
                          <a href="https://openai.com/policies/privacy-policy" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">
                            https://openai.com/policies/privacy-policy
                          </a>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <p className="leading-relaxed mt-4">
                  Note: We may add additional service providers as we grow. We will update this policy accordingly.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Behavioral Remarketing</h2>
                <p className="leading-relaxed">
                  Knowtly may use remarketing services to advertise on third-party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Payments</h2>
                <p className="leading-relaxed">
                  We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g., payment processors).
                </p>
                <p className="leading-relaxed mt-4">
                  We will not store or collect your payment card details. That information is provided directly to our third-party payment processors, whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Links to Other Sites</h2>
                <p className="leading-relaxed">
                  Our Service may contain links to other sites that are not operated by us. If you click a third-party link, you will be directed to that third party&apos;s site. We strongly advise you to review the Privacy Policy of every site you visit.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Children&apos;s Privacy</h2>
                <p className="leading-relaxed">
                  Our Services are not intended for use by children under the age of 18 (&quot;Child&quot; or &quot;Children&quot;).
                </p>
                <p className="leading-relaxed mt-4">
                  We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Changes to This Privacy Policy</h2>
                <p className="leading-relaxed">
                  We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
                </p>
                <p className="leading-relaxed mt-4">
                  We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective, and update the &quot;effective date&quot; at the top of this Privacy Policy.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-white mt-8 mb-4">Contact Us</h2>
                <p className="leading-relaxed">
                  If you have any questions about this Privacy Policy, please contact us by email: support@knowtly.app
                </p>
              </section>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}
